[versions]
scala-library = "2.12.15"
spark = "3.5.1"

[plugins]
shadow = "com.gradleup.shadow:8.3.0"
scala-extras = "io.github.tassiluca.gradle-scala-extras:3.13.3"

[libraries]
scala-library = { module = "org.scala-lang:scala-library", version.ref = "scala-library" }
scala-reflect = { module = "org.scala-lang:scala-reflect", version.ref = "scala-library" }
scala-compiler = { module = "org.scala-lang:scala-compiler", version.ref = "scala-library" }
spark-core = { module = "org.apache.spark:spark-core_2.12", version.ref = "spark" }
spark-sql = { module = "org.apache.spark:spark-sql_2.12", version.ref = "spark" }
spark-hive = { module = "org.apache.spark:spark-hive_2.12", version.ref = "spark" }


[bundles]
scala = ["scala-library", "scala-reflect", "scala-compiler"]
spark = ["spark-core", "spark-sql", "spark-hive"]
